import streamlit as st
import pandas as pd
from doc2image import api


def render_output(summary_session_id: int):
    """
    Renders the output of a generation session using a clean, tabbed interface.

    Args:
        summary_session_id (int): The ID of the document summary session to display.
    """
    summary_session = api.get_summary_by_id(summary_session_id)
    if not summary_session:
        st.error("Could not find the selected session. It may have been deleted.")
        return

    # A clear subheader indicating which document's results are being shown.
    st.subheader(f"Results for: `{summary_session.document.name}`")

    # Use st.tabs to organize the output neatly and prioritize the most important information.
    tab_ideas, tab_summary, tab_details = st.tabs(
        ["🖼️ Image Ideas", "📝 Summary", "⚙️ Generation Details"]
    )

    # --- Tab 1: Image Ideas (The primary result) ---
    with tab_ideas:
        st.markdown("#### Here are your generated image ideas!")
        prompts = [
            p.prompt for ps in summary_session.image_prompt_sessions for p in ps.prompts
        ]

        if prompts:
            # Display ideas in a DataFrame for a clean, table-like view.
            df_prompts = pd.DataFrame({"Image Idea": prompts})
            df_prompts.index = range(1, len(df_prompts) + 1)
            st.dataframe(df_prompts, use_container_width=True)

            # Provide a convenient download button for the generated ideas.
            st.download_button(
                label="⬇️ Download All Ideas",
                data="\n\n".join(prompts),
                file_name=f"{summary_session.document.name.split('.')[0]}_ideas.txt",
                mime="text/plain",
            )
        else:
            st.info("No image ideas were generated for this document session.")

    # --- Tab 2: Document Summary ---
    with tab_summary:
        st.markdown("#### Document Summary")
        st.markdown(
            "This is the summary generated by the AI based on the document's content, which was used to create the image ideas."
        )
        # Use a text_area for easy reading and copying of the summary.
        st.text_area(
            "Summary",
            summary_session.document_summary,
            height=250,
            label_visibility="collapsed",
        )
        st.download_button(
            label="⬇️ Download Summary",
            data=summary_session.document_summary,
            file_name=f"{summary_session.document.name.split('.')[0]}_summary.txt",
            mime="text/plain",
        )

    # --- Tab 3: Generation Details (For advanced users) ---
    with tab_details:
        st.markdown("#### Technical Details of the Generation Process")

        col1, col2 = st.columns(2)
        with col1:
            st.markdown(
                f"""
                - **Document:** `{summary_session.document.name}`
                - **Generation Date:** `{summary_session.generation_date.strftime('%Y-%m-%d %H:%M')}`
                - **LLM Used:** `{summary_session.llm_model.name} ({summary_session.llm_model.provider.name})`
                """
            )

        with st.expander("⚙️ View All Parameters"):
            # Consolidate all technical settings into one expandable section.
            st.markdown("**Document Summary LLM Settings**")
            st.code(
                f"Temperature: {summary_session.llm_temperature}\n"
                f"Top-p: {summary_session.llm_top_p}\n"
                f"Top-k: {summary_session.llm_top_k}\n"
            )
            if summary_session.image_prompt_sessions:
                st.markdown("**Image Idea LLM Settings**")
                st.code(
                    f"Temperature: {summary_session.image_prompt_sessions[0].llm_temperature}\n"
                    f"Top-p: {summary_session.image_prompt_sessions[0].llm_top_p}\n"
                    f"Top-k: {summary_session.image_prompt_sessions[0].llm_top_k}\n"
                )

            st.markdown("**Chunking & Summary Settings**")
            st.code(
                f"Chunk Size: {summary_session.chunk_size}\n"
                f"Chunk Overlap: {summary_session.chunk_overlap}\n"
                f"Max Chunk Summary Size: {summary_session.max_chunk_summary_size}\n"
                f"Max Document Summary Size: {summary_session.max_document_summary_size}\n"
                f"Chunk Count: {len(summary_session.chunk_summaries)}"
            )

        st.markdown("#### Chunk-by-Chunk Summaries")
        chunk_data = [
            {"Chunk": i + 1, "Summary": chunk.chunk_summary}
            for i, chunk in enumerate(summary_session.chunk_summaries)
        ]
        if chunk_data:
            st.dataframe(
                pd.DataFrame(chunk_data), use_container_width=True, hide_index=True
            )
        else:
            st.info("No chunk summaries were generated for this session.")
